### ISSUE TITLE
主题很好看，据实能不能把资源文件放到自己服务器中

### ISSUE THREAD

**Issue by appdev** [lialun/EverBlog#1]
主题确实很好看，暗色亮色切换也很好，资源文件放到又拍云中也没什么不好，但是如果网站全部是https的话，又拍云的资源又不支持https导致有时候会报错。

**Comment by lialun** [comment]
您好。我本来设想的是github中的代码是从本地读取资源。又拍云加载资源让有需求的人自己来修改源码。这样就符合您的需求了。
但是最近公司太忙，快过年了嘛。我只好先把这样的半成品放上来。
我下周周末尽量抽出时间来先把资源改到本地加载。满足您的需求。

**Comment by appdev** [comment]
谢谢。如果您比较忙的话也不用太急，提前祝您您年快乐。

**Comment by lialun** [comment]
已经好了。您可以看下哈

**Comment by appdev** [comment]
谢谢，我已经安装在用了。主题很有特色，感觉很有创意，第一次看到有有暗色亮色的主题，不错！

**Comment by lialun** [comment]
谢谢支持，欢迎多提意见、贡献代码~~
