### ISSUE TITLE
Horizontal scroll bar on the bottom

### ISSUE THREAD

**Issue by pointcache** [lialun/EverBlog#10]
I have one bar at the bottom of my blog, it is breaking the visuals of the blog at
www.pointcache.com

**Comment by lialun** [comment]
I just fix it. download the newest version and have a try?

**Comment by pointcache** [comment]
I tried, it fixed the horizontal but introduced new issue with pages not displaying correctly. 
check this http://www.pointcache.com/unity-tutorial-creating-internal-trigger-zones-for-your-game/
