### ISSUE TITLE
Bugged pages after update

### ISSUE THREAD

**Issue by pointcache** [lialun/EverBlog#11]
pages now are not displayed correctly after last commit http://prntscr.com/d7oywy

**Comment by pointcache** [comment]
http://www.pointcache.com/unity-tutorial-creating-internal-trigger-zones-for-your-game/

**Comment by lialun** [comment]
odd...it's good on my blog..i'm so sorry
I modify it again,and I removed nice scroll~please try again~

**Comment by pointcache** [comment]
Fixed
