### ISSUE TITLE
Always Get an Error

### ISSUE THREAD

**Issue by ghost** [lialun/EverBlog#2]
失败，请稍后再试！
Every time, even on mobile, even when only loading 1 article on the home page.
This is sad, I really like this theme.

**Comment by lialun** [comment]
What's your blog's URL?Can I have a look at your blog?

**Comment by jerusalemdax** [comment]
in file  content/themes/EverBlog/partials/config.hbs
default_post must be set to available url to prevent this error, which the author doesn't mention.

**Comment by xdjinjian** [comment]
@lialun 灰常好看 棒棒哒！！！！！！！！

**Comment by lialun** [comment]
fixed
