### ISSUE TITLE
package.json: Value for field version, 0.2 does not match forma

### ISSUE THREAD

**Issue by SabeBarker** [lialun/EverBlog#7]
Hello,

When the theme is uploaded I receive the error:
```
package.json: Value for field version, 0.2 does not match format: /^[0-9]+\.[0-9]+[0-9+a-zA-Z\.\-]+$/
```

It doesn't seem to cause an issue when the theme is activated though.

**Comment by pointcache** [comment]
yeah throws the error but works

**Comment by lialun-xm** [comment]
What version of ghost you are using？

**Comment by pointcache** [comment]
0.11.3
its the one that comes preinstalled with digitalocean droplet (automatic deploy) so i wont change it because im not a webdev and installing such stuff is always a pain for me

**Comment by lialun** [comment]
fixed
