### ISSUE TITLE
Chinese (?) letters left in some parts.

### ISSUE THREAD

**Issue by pointcache** [lialun/EverBlog#8]
you can see here, how do i fix this? (im not a webdev :| )
http://prntscr.com/d664eg

**Comment by pointcache** [comment]
To anyone with same issue you need to change these files 
http://prntscr.com/d66amt

**Comment by pointcache** [comment]
you need to reboot ghost (i just rebooted the server)

**Comment by pointcache** [comment]
just make sure it looks like this {date format="YYYY/MM/DD"}}

and in tag-blog-list

```
<div class="tag-stats-count">
                 {{pagination.total}} useless posts
            </div>
```

**Comment by lialun-xm** [comment]
I'm so sorry that ghost i18n is not work for now, and i do not expect that so many english language people use this theme😄. next version i will change all the chinese to english.

**Comment by pointcache** [comment]
Thank you! Well obviously everyone will use it cuz it's the best theme out there for devs.

**Comment by pointcache** [comment]
btw my blog www.pointcache.com
