### ISSUE TITLE
How to disable the scrolling thing?

### ISSUE THREAD

**Issue by pointcache** [lialun/EverBlog#9]
I have a feeling the scrolling is causing problems because sometimes im unable to click on the links, can you tell me how to disable it?

**Comment by lialun** [comment]
unable to click on the links? computer or mobile?can it be reappear?

**Comment by pointcache** [comment]
i deleted nicescroll.js by advice of my friend and it works, the links now are clickable.
Im on desctop win10, Cent browser.

**Comment by pointcache** [comment]
fixed
